# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454726c6c4ed69d6d059e3c9e617931650c4b6e8e79b4fb2c42d88febeeb7bfb60d2d0c274e1ede7882b3c50f6cc19d42cfc0277a4d714034f35612708e0695c

test:
  secret_key_base: e5a134fca293a4c965b6b4b584b909fe2f8cb7bef1e43200c4790efe6dd9a00a35692b405eec2d35f211e63fdcb6f54329dc7a8251000da886ca908b237dba5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
